SUPABASE_URL="https://bketfhsqaofwijdchfke.supabase.co"
SUPABASE_ANON_KEY="senin_anon_keyin"
SUPABASE_SERVICE_KEY="service_role_key"
OPENAI_API_KEY="openai_key"

[auth]
redirect_uri="https://optiflow-enterprise-ewxicdsl96crsq2ycortqo.streamlit.app/oauth2callback"
cookie_secret="uzun_random_bir_secret"
client_id="google_client_id"
client_secret="google_client_secret"
server_metadata_url="https://accounts.google.com/.well-known/openid-configuration"